### ISSUE TITLE
AutoSynthesis Lua Addon

### ISSUE THREAD

**Issue by Neovivi** [lorand-ffxi/addons#15]
Hello autoSynth addon somethings up with it, when /autoSynth start is loaded you get a note in game 
Syntheses cancelled
autoSynth on
autosynth off

anything i might be doing wrong? i followed your tutorial setting it all up itis loaded when i synth manualy it does show moon phase weather synth NQ or HQ etc so it appears tobe functioning right just not automaticaly crafting

**Comment by lorand-ffxi** [comment]
Apologies, I was busy with school, then with work, and I haven't played FFXI in a while.  Are you still having issues?  Sometimes updates would break this until the Windower team pushed their luacore updates.

**Comment by lorand-ffxi** [comment]
Everything seems to be working fine.  I made some adjustments recently, but nothing really about the repeat synth logic.  It simply runs /lastsynth repeatedly.  "Synthesis cancelled." is from the game, and autoSynth stops its loop when it sees it.  It usually means your inventory is full, or you don't have the proper materials or crystals.
