### ISSUE TITLE
Spellspammer Broken

### ISSUE THREAD

**Issue by lobo-** [lorand-ffxi/addons#16]
Maybe it's just me but, Spellspammer loads, but no longer executes spells or seems to work. perhaps i'm missing a run command once u load the addon ? but their is no info with this addon

**Comment by lorand-ffxi** [comment]
I'll take a look in to this soon.  I only recently returned to FFXI.

**Comment by lorand-ffxi** [comment]
It looks like I wrote it so you have to be engaged and have a target in order for it to run.  I may have broken it at some point inadvertently.  I got it working right now to cycle through spells for skilling up.  I'll probably try to clean it up a bit and push the changes soon.

**Comment by lorand-ffxi** [comment]
If you are still having issues with this addon, I would now recommend using HealBot instead.  You can spam spells or abilities with the following commands, and engaging an enemy:
//lua load healbot
//hb on; hb spam stone; hb spam on; hb independent
